language: php

sudo: false

git:
  depth: 5

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
  fast_finish: true

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit --verbose